### ISSUE TITLE
bug with +at(slice-name)

### ISSUE THREAD

**Issue by Djules** [jescalan/rupture#27]
Slice names is an excellent enhancement, unfortunately I found a bug with `+at()` mixin if you use the name of the slice instead of its index.

``` stylus
.test
  +at('xs')
    color: #fff
```

compiles to 

``` css
@media only screen and (max-width: 0) {
    .test {
        color: #fff;
    }
}
```

instead of 

``` css
@media only screen and (max-width: 400px) {
    .test {
        color: #fff;
    }
}
```
