### ISSUE TITLE
`to()` conflicts with CSS3 linear-gradient syntax (and nib)

### ISSUE THREAD

**Issue by bryanforbes** [jescalan/rupture#37]
I'm currently doing something along these lines:

``` css
@require 'nib';
@require 'rupture';

.some-thing {
        background: linear-gradient(to bottom, #F8F8F8, #F4F4F4);
}

/* later on I use rupture, so I require it for a reason */
```

This ends up generating the following:

``` css
.some-thing {
  background: -webkit-linear-gradient(to(scale-point, anti-overlap, density, orientation, use-device-width) bottom, #f8f8f8, #f4f4f4);
  background: -moz-linear-gradient(to(scale-point, anti-overlap, density, orientation, use-device-width) bottom, #f8f8f8, #f4f4f4);
  background: -o-linear-gradient(to(scale-point, anti-overlap, density, orientation, use-device-width) bottom, #f8f8f8, #f4f4f4);
  background: -ms-linear-gradient(to(scale-point, anti-overlap, density, orientation, use-device-width) bottom, #f8f8f8, #f4f4f4);
  background: linear-gradient(to(scale-point, anti-overlap, density, orientation, use-device-width) bottom, #f8f8f8, #f4f4f4);
}
```

One workaround I've used is to change `to bottom` to `unquote('to bottom')`, but that's not really in the spirit of nib. I haven't thought about it much, but it seems like the only solution aside from using `unquote()` is to change the name of `to()` and/or prefix all rupture functions with something to avoid conflicts with CSS features.
