### ISSUE TITLE
No @media exported when I upgrade from 0.4.0 to 0.5.0

### ISSUE THREAD

**Issue by camilleb** [jescalan/rupture#42]
Hi,

I have no rules @media ... when I upgrade from 0.4.0 to 0.5.0.

Here an example:

In my file app.styl

``` css
.wrap-page
    padding 0 30px
    cf()
    +from(screen-xs)
        padding 0 50px
    +from(screen-sm)
        padding 0 70px
    +from(screen-md)
        padding 0 100px
    +from(screen-md)
        padding 0 130px
```

With 0.4.0 I have:

``` css
.wrap-page {
  padding: 0 30px;
  *zoom: 1;
}
.wrap-page:before,
.wrap-page:after {
  content: '';
  display: table;
}
.wrap-page:after {
  clear: both;
}
@media only screen and (min-width: 480px) {
  .wrap-page {
    padding: 0 50px;
  }
}
@media only screen and (min-width: 768px) {
  .wrap-page {
    padding: 0 70px;
  }
}
@media only screen and (min-width: 992px) {
  .wrap-page {
    padding: 0 100px;
  }
}
@media only screen and (min-width: 992px) {
  .wrap-page {
    padding: 0 130px;
  }
}
```

With 0.5.0 I get:

``` css
.wrap-page {
  padding: 0 30px;
  *zoom: 1;
from(480px)
from(768px)
from(992px)
from(992px)
}
.wrap-page:before,
.wrap-page:after {
  content: '';
  display: table;
}
.wrap-page:after {
  clear: both;
}
```

Is there something I do wrong?
