### ISSUE TITLE
Above mixin not working

### ISSUE THREAD

**Issue by jescalan** [jescalan/rupture#9]
Not sure how nobody has noticed this, but the `+above` mixin is not working correctly. The source of the issue is [this line](https://github.com/jenius/rupture/blob/master/rupture/index.styl#L45) if im not mistaken. This assumes that while, if the min is zero, there is no lower bound, there is _always_ an upper bound. With regard to `above`, this is certainly not correct. It's easy to show this bug as well:

``` styl
+above(500px)
  color: red
```

compiles to

``` css
@media only screen and (min-width: 500px) and (max-width: 1050px) {
  color: red
}
```

Since `above` is aliased to `from`, it always maps the value relative to the top point on the scale, which is not the correct behavior. Although the bug might not appear with simple testing, this is obviously incorrect output.
